apiVersion: v1
kind: Service
metadata:
  name: my-ml-app-service
spec:
  selector:
    app: my-ml-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer  # Exposes the app to the internet
